categorical_features:
  - "Glascow coma scale eye opening"
  - "Glascow coma scale motor response"
  - "Glascow coma scale verbal response"
  - "Glascow coma scale total"
excludes:
  - "Hours"

n_epochs: 100
lr: 0.0002
loss_type: "BCE"

batch_size: 32
cutoff_seq_len: 76

device: cuda

save_model_path: "_saved_models/"
model_name: "RemoteTest"
mimic_data_path: "./data/in-hospital-mortality/"
datadir: "./data/my_mimic/"

data_suffix: "_allData.pkl"

model_n_layers: 1
model_dropout: 0.3
model_bias: True
model_bidirectional: True
model_hdim: 32


merge_time_size: 1.0
input_concat_w_mask: False
data_preproc: None
hours_to_eval: 48.0

load_model: True
load_data: True
load_model_path: "_saved_models/PresentationTesting_epoch18_aucroc0.83710.pt"

halt_and_show_matplotlib: False
model_class: benchmark_lstm
model_type: lstm
explanation_methods:
  num_background_samples: 0.75
  test_idxs:

  methods:
    windowshap:
      num_background_used: 100
      window_len: 1
      wrap_model: True
    comte:
      num_background_used: 100
      max_n_feats: 3
    anchors:
      num_background_used: 100


throw_errors: False

n_instances_to_explain: 4
n_rand_seed_to_try: 1
n_trials_per_rand_seed: 1


load_autoencoder: False
