categorical_features:
  - "Glascow coma scale eye opening"
  - "Glascow coma scale motor response"
  - "Glascow coma scale verbal response"
excludes:
  - "Hours"

n_epochs: 50
lr: 0.001
loss_type: "BCE"

batch_size: 32
cutoff_seq_len: 76

device: cuda

save_model_path: "_saved_models/"
model_name: "PresentationTesting"
mimic_data_path: "./data/in-hospital-mortality/"
datadir: "./data/my_mimic/"

data_suffix: "_allData.pkl"

model_n_layers: 2
model_dropout: 0.3
model_bias: True
model_bidirectional: True
model_hdim: 16
load_model_path: "_saved_models/LSTM_mine_epoch31_aucroc0.82408.pt"

merge_time_size: 1.0
input_concat_w_mask: False
data_preproc: None
hours_to_eval: 48.0

load_model: True
load_data: True

model_class: benchmark_lstm
model_type: lstm
explanation_methods:
  n_background_data: 2000
  test_idxs:
  window_shap:
    window_len: 1
    wrap_model: True
    num_background: 1

throw_errors: False
gen_presentation_data: True
presentation_examples_per_category: 1
