categorical_features:
  - "Glascow coma scale eye opening"
  - "Glascow coma scale motor response"
  - "Glascow coma scale verbal response"
  - "Glascow coma scale total"
excludes:
  - "Hours"

device: cuda

save_model_path: D:/research/craven/baselines/explanationTesting/_saved_models
mimic_data_path: D:/research/craven/baselines/explanationTesting/data/in-hospital-mortality
datadir: D:/research/craven/baselines/explanationTesting/data/my_mimic
data_suffix: _allData.pkl

training:
  model:
    model_n_layers: 1
    model_dropout: 0.3
    model_bias: True
    model_bidirectional: True
    model_hdim: 32
    model_class: benchmark_lstm
  train:
    n_epochs: 100
    lr: 0.0001
    batch_size: 32
    loss_type: BCE
  data:
    max_seq_len: 76
    merge_time_size: 1.0
    n_hours_to_use: 48.0
    input_concat_w_mask: False
    data_preproc: None

experiment:
  name: exp_cleanup
  load_model: False
  load_data: False
  load_model_path: D:/research/craven/baselines/explanationTesting/_saved_models/PresentationTesting_epoch18_aucroc0.83710.pt
reporting:
  throw_errors: False

#model_type: lstm



